# Generated by Django 5.2.7 on 2026-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacientes_atendidos', models.IntegerField(default=0, verbose_name='Pacientes atendidos')),
                ('medicos_aliados', models.IntegerField(default=0, verbose_name='Médicos aliados')),
                ('centros_de_salud', models.IntegerField(default=0, verbose_name='Centros de salud')),
                ('municipios', models.IntegerField(default=0, verbose_name='Municipios alcanzados')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadísticas del Programa',
            },
        ),
    ]
